--DROP DATABASE ATIVIDADE
DROP DATABASE ATIVIDADE;

--CREATE DATABASE ATIVIDADE
CREATE DATABASE ATIVIDADE;

--USE DATABASE ATIVIDADE
USE ATIVIDADE;

CREATE TABLE CLIENTE(
	ID INT IDENTITY(1,1) NOT NULL, -- AUTO INCREMENTO
	NOME VARCHAR(50),
	TELEFONE VARCHAR(50),
	EMAIL VARCHAR(100),
	SENHA VARCHAR(40),
	CARTAOCREDITO SMALLMONEY,
	CONSTRAINT PK_CLIENTE PRIMARY KEY(ID)
);
GO

CREATE TABLE DOCUMENTARIOS(
	ID INT IDENTITY(1,1) NOT NULL, -- AUTO INCREMENTO
	NOME VARCHAR(50),
	IDIOMA VARCHAR(50),
	LEGENDA VARCHAR(50),
	ANO CHAR(4),
	DURACAO VARCHAR(50),
	TEMPORADA VARCHAR(100),
	NUMEPS VARCHAR(200),
	CONSTRAINT PK_DOCUMENTARIOS PRIMARY KEY(ID)
);
GO

CREATE TABLE FILMES(
	ID INT IDENTITY(1,1) NOT NULL, -- AUTO INCREMENTO
	NOME VARCHAR(50),
	IDIOMA VARCHAR(50),
	LEGENDA VARCHAR(50),
	ANO CHAR(4),
	CONSTRAINT PK_FILMES PRIMARY KEY(ID)
);
GO

CREATE TABLE MENSALIDADE(
	ID INT IDENTITY(1,1) NOT NULL, -- AUTO INCREMENTO
	VALOR VARCHAR(50),
	RENOVACAOASSINATURA BIT NOT NULL,
	DATAPAGAMENTO DATE,
	CONSTRAINT PK_MENSALIDADE PRIMARY KEY(ID),
	CONSTRAINT CLIENTE FOREIGN KEY(FK_CLIENTE)
	REFERENCES DBO.CLIENTE(ID)
);
GO

CREATE TABLE VIDEOS(
	ID INT IDENTITY(1,1) NOT NULL, -- AUTO INCREMENTO
	NOME VARCHAR(50),
	TITULO VARCHAR(50),
	GENERO VARCHAR(30),
	DURACAO TIME(50),
	IDIOMA VARCHAR(50),
	NUMEPS INT VARCHAR(200),
	LEGENDAS VARCHAR(50),
	CONSTRAINT PK_VIDEOS PRIMARY KEY(ID)
);
GO

SET IDENTITY_INSERT dbo.CLIENTE ON
INSERT INTO DBO.CLIENTE (ID, NOME, TELEFONE, EMAIL, SENHA, CARTAOCREDITO) VALUES (1, 'CLAUDIO', '83987654321', 'claudio@gmail.com', 123456, '5546846541213');
INSERT INTO DBO.CLIENTE (ID, NOME, TELEFONE, EMAIL, SENHA, CARTAOCREDITO) VALUES (2, 'CLEYSON', '85988792849', 'cleyson@hotmail.com', 123456, '23465482');
INSERT INTO DBO.CLIENTE (ID, NOME, TELEFONE, EMAIL, SENHA, CARTAOCREDITO) VALUES (3, 'LUCAS', '83988978535', 'lucas@gmail.com', Lucas123, '154642197382');
INSERT INTO DBO.CLIENTE (ID, NOME, TELEFONE, EMAIL, SENHA, CARTAOCREDITO) VALUES (4, 'JUNIOR', '83982485986', 'junior@hotmail.com', Junior123 , '4782131684');
INSERT INTO DBO.CLIENTE (ID, NOME, TELEFONE, EMAIL, SENHA, CARTAOCREDITO) VALUES (5, 'JOAO', '8399678295', 'joao@outlook.com', Jose123, '123789454654');
SET IDENTITY_INSERT dbo.CLIENTE OFF

ALTER TABLE DBO.CLIENTE.NOME MODIFY COLUMN C
	
SELECT * FROM DBO.CLIENTE c 

SET IDENTITY_INSERT dbo.DOCUMENTARIOS ON
INSERT INTO dbo.DOCUMENTARIOS (ID, NOME, IDIOMA, LEGENDA, ANO, TEMPORADA, DURACAO, NUMEPS) VALUES (1, 'AS TRANÇAS DO REI CARECA', 'PORTUGUES', 'FALSE', '2022-05-05', 1, '02:14', 15);
INSERT INTO dbo.DOCUMENTARIOS (ID, NOME, IDIOMA, LEGENDA, ANO, TEMPORADA, DURACAO, NUMEPS) VALUES (2, 'DOM QUIXOTE DE LA MANCHA', 'INGLES', 'TRUE', '2012-07-05', 1, '01:45', 8);
INSERT INTO dbo.DOCUMENTARIOS (ID, NOME, IDIOMA, LEGENDA, ANO, TEMPORADA, DURACAO, NUMEPS) VALUES (3, 'POEIRA EM ALTO MAR', 'PORTUGUES', 'TRUE', '2015-05-25', 1, '00:51', 20);
INSERT INTO dbo.DOCUMENTARIOS (ID, NOME, IDIOMA, LEGENDA, ANO, TEMPORADA, DURACAO, NUMEPS) VALUES (4, 'A VOLTA DOS QUE NÃO FORAM', 'PORTUGUES', 'FALSE', '2008-07-14', 1, '00:30', 7);
SET IDENTITY_INSERT dbo.DOCUMENTARIOS OFF

SELECT * FROM DBO.DOCUMENTARIOS d 

SET IDENTITY_INSERT dbo.FILMES  ON
INSERT INTO DBO.FILMES (ID, NOME, IDIOMA, LEGENDA, ANO) VALUES (001, 'Convite Maldito', 'INGLES', 'TRUE', '2022-08-25');
INSERT INTO DBO.FILMES (ID, NOME, IDIOMA, LEGENDA, ANO) VALUES (002, 'Sorria', 'INGLES', 'TRUE', '2022-07-29');
INSERT INTO DBO.FILMES (ID, NOME, IDIOMA, LEGENDA, ANO) VALUES (003, 'Halloween Ends - O Acerto de Contas Final', 'INGLES', 'TRUE', '2022-10-13');
INSERT INTO DBO.FILMES (ID, NOME, IDIOMA, LEGENDA, ANO) VALUES (004, 'A Mulher Rei', 'PORTUGUES', 'TRUE', '2022-07-22');
INSERT INTO DBO.FILMES (ID, NOME, IDIOMA, LEGENDA, ANO) VALUES (005, 'Amsterdam', 'INGLES', 'TRUE', '2022-10-06');
SET IDENTITY_INSERT dbo.FILMES  OFF

SELECT * FROM DBO.FILMES f 

SET IDENTITY_INSERT dbo.MENSALIDADE ON
INSERT INTO DBO.MENSALIDADE (ID, VALOR, RENOVACAOASSINATURA, IDCLIENTE, DATAPAGAMENTO) VALUES (01, 15.50, 'NÃO', 1, '2022-09-11');
SET IDENTITY_INSERT dbo.MENSALIDADE OFF

SELECT * FROM DBO.MENSALIDADE m 

SET IDENTITY_INSERT dbo.SERIES ON
INSERT INTO DBO.SERIES (ID, NOME, TEMPORADA, DESCRICAO, ANO, DURACAO, IDIOMA, NUMEPS, LEGENDAS) VALUES (1, 'O Clube da Meia Noite', 2, 'Sete jovens com doenças terminais passam os seus últimos dias de vida no hospício', '2022', '05:15', 'ALEMÃO', 7, 'TRUE');
INSERT INTO DBO.SERIES (ID, NOME, TEMPORADA, DESCRICAO, ANO, DURACAO, IDIOMA, NUMEPS, LEGENDAS) VALUES (2, '9-1-1', 2, '911 é o número de telefone discado em casos de emergência.', '2018', '00:35:15', 'INGLÊS', 8, 'TRUE');
INSERT INTO DBO.SERIES (ID, NOME, TEMPORADA, DESCRICAO, ANO, DURACAO, IDIOMA, NUMEPS, LEGENDAS) VALUES (3, 'Ruptura', 5, 'Cinco funcionários aceitam participar de um procedimento que separa permanentemente suas memórias pessoais das do trabalho.', '2022', '00:55:20', 'INGLÊS', 15, 'TRUE');
INSERT INTO DBO.SERIES (ID, NOME, TEMPORADA, DESCRICAO, ANO, DURACAO, IDIOMA, NUMEPS, LEGENDAS) VALUES (4, 'O Filho BAstardo do Diabo', 1, 'O Filho Bastardo do Diabo é uma série britânica de fantasia original Netflix baseada na trilogia de livros Half Bad, escrita por Sally Green.', '2022', '00:55:15', 'ALEMÃO', 9, 'TRUE');
INSERT INTO DBO.SERIES (ID, NOME, TEMPORADA, DESCRICAO, ANO, DURACAO, IDIOMA, NUMEPS, LEGENDAS) VALUES (5, 'Periféricos', 5, 'Depois que seu irmão consegue um emprego em uma empresa de tecnologia, Flynn descobre um mundo virtual que pode estar mais próximo da realidade do que eles imaginam.', '2022', '00:47:35', 'PORTUGUES', 20, 'TRUE');
SET IDENTITY_INSERT dbo.SERIES OFF

SELECT * FROM dbo.SERIES s 

SET IDENTITY_INSERT dbo.VIDEOS  ON
INSERT INTO DBO.VIDEOS (ID, TITULO, GENERO, DURACAO, PRODUTORA, SINOPSE) VALUES (1, 'VIDEO 1', 'F', '05:00', 'ANONIMA', 'ALGO ENGRAÇADO');
INSERT INTO DBO.VIDEOS (ID, TITULO, GENERO, DURACAO, PRODUTORA, SINOPSE) VALUES (2, 'VIDEO 2', 'M', '08:13', 'ANONIMA', 'ALGO LEGAL');
INSERT INTO DBO.VIDEOS (ID, TITULO, GENERO, DURACAO, PRODUTORA, SINOPSE) VALUES (3, 'VIDEO 3', 'F', '06:52', 'ANONIMA', 'ENGRAÇADO');
INSERT INTO DBO.VIDEOS (ID, TITULO, GENERO, DURACAO, PRODUTORA, SINOPSE) VALUES (4, 'VIDEO 4', 'F', '04:41', 'VIDEOS ONLINE', 'ALGO');
INSERT INTO DBO.VIDEOS (ID, TITULO, GENREO, DURACAO, PRODUTORA, SINOPSE) VALUES (5, 'VIDEO 5', 'M', '05:25', 'PESSOAL', 'ANONIMO');
SET IDENTITY_INSERT dbo.VIDEOS  OFF

SELECT * FROM DBO.VIDEOS v 